sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t clubdeuce/docker-react .

script:
  - docker run -e CI=true clubdeuce/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-122018988684"
  bucket_path: "Docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"